In [1]:
import torch
import numpy as np

# 从 list 变为一个 tensor
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

# 从 numpy 数组中变为一个 tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 从另一个 tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


# 随机
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9934, 0.0650],
        [0.3928, 0.5111]]) 

Random Tensor: 
 tensor([[0.2176, 0.3772, 0.1283],
        [0.2462, 0.4475, 0.8900]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
